"""
Parser Bank for OpenStack_2k
Generated by QwenLog
Model: Qwen2.5-Coder-7B
Generated: 2026-01-21 16:51:22
Templates: 25
"""

from typing import Dict, Optional

def is_log_template_0(log):
    return "GET" in log and "status:" in log and "len:" in log and "time:" in log

def parse_log_template_0(log):
    result = {
        'template_id': 0,
        'template': '<*> "GET <*>" status: <*> len: <*> time: <*>.<*>'
    }
    try:
        parts = log.split('"')
        method = parts[1].split()[0]
        path = parts[1].split()[1]
        status = int(parts[2].split()[1])
        length = int(parts[3].split()[1])
        time = float(parts[4].split()[1])
        result.update({
            'method': method,
            'path': path,
            'status': status,
            'length': length,
            'time': time
        })
    except (IndexError, ValueError) as e:
        pass
    return result

def is_log_template_1(log):
    return "image" in log and "checking" in log

def parse_log_template_1(log):
    try:
        parts = log.split(" at (")[0].split(" ")
        template_id = "template_id_1"
        template = "image <*> at (<*>): checking"
        var1 = parts[1]
        var2 = parts[3]
        return {
            'template_id': template_id,
            'template': template,
            'var1': var1,
            'var2': var2
        }
    except Exception as e:
        return {
            'template_id': "template_id_1",
            'template': "image <*> at (<*>): checking",
            'error': str(e)
        }

def is_log_template_2(log):
    return "image" in log and "at (" in log and "in use:" in log and "on this node" in log and "local," in log

def parse_log_template_2(log):
    result = {
        'template_id': 'template_2',
        'template': 'image <*> at (<*>): in use: on this node <*> local, <*> on other nodes sharing this instance storage'
    }
    try:
        parts = log.split(": in use:")
        if len(parts) != 2:
            return result
        usage_info = parts[1].strip()
        local_parts = usage_info.split(" on this node ")
        if len(local_parts) != 2:
            return result
        local_info = local_parts[0].strip()
        other_parts = local_parts[1].split(", ")
        if len(other_parts) != 2:
            return result
        local_count = int(other_parts[0].split(" ")[0])
        other_count = int(other_parts[1].split(" ")[0])
        result['local_count'] = local_count
        result['other_count'] = other_count
        result['image_id'] = log.split("image ")[1].split(" at")[0].strip()
        result['path'] = log.split(" at (")[1].split("):")[0].strip()
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_3(log_line):
    return "Active base files:" in log_line

def parse_log_template_3(log_line):
    try:
        parts = log_line.split(": ")
        if len(parts) != 2 or parts[0] != "Active base files":
            return {'template_id': 3, 'template': 'Active base files: <*>', 'error': 'Invalid format'}
        return {'template_id': 3, 'template': 'Active base files: <*>', 'path': parts[1]}
    except Exception as e:
        return {'template_id': 3, 'template': 'Active base files: <*>', 'error': str(e)}

def is_log_template_4(log):
    return "POST" in log and "status:" in log and "len:" in log and "time:" in log

def parse_log_template_4(log):
    try:
        parts = log.split()
        ip = parts[0]
        method_url = parts[1]
        status = int(parts[parts.index("status:") + 1].split(":")[1])
        length = int(parts[parts.index("len:") + 1].split(":")[1])
        time = float(parts[parts.index("time:") + 1].split(":")[1])
        return {
            'template_id': 4,
            'template': "<*> \"POST <*>\", status: <*>, len: <*>, time: <*>,.<*>",
            'ip': ip,
            'method_url': method_url,
            'status': status,
            'length': length,
            'time': time
        }
    except (IndexError, ValueError) as e:
        return {
            'template_id': 4,
            'template': "<*> \"POST <*>\", status: <*>, len: <*>, time: <*>,.<*>"
        }

def is_log_template_5(log):
    return "instance:" in log and "VM Resumed" in log and "(Lifecycle Event)" in log

def parse_log_template_5(log):
    try:
        parts = log.split()
        instance_id = parts[1].strip('[]')
        return {
            'template_id': 5,
            'template': '[instance: <*>] VM Resumed (Lifecycle Event)',
            'instance_id': instance_id
        }
    except Exception as e:
        return {
            'template_id': 5,
            'template': '[instance: <*>] VM Resumed (Lifecycle Event)',
            'error': str(e)
        }

def is_log_template_6(log):
    return "[instance:" in log and "During sync_power_state" in log and "the instance" in log and "Skip." in log

def parse_log_template_6(log):
    result = {'template_id': 6, 'template': '[instance: <*>] During sync_power_state the instance has a pending task (spawning). Skip.'}
    try:
        parts = log.split(']')
        if len(parts) < 2:
            return result
        instance_part = parts[0].split(': ')[1]
        result['instance'] = instance_part.strip()
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_7(log_line):
    return "Unknown base file:" in log_line

def parse_log_template_7(log_line):
    try:
        parts = log_line.split(": ")
        if len(parts) != 2 or parts[0] != "Unknown base file":
            return {'template_id': 7, 'template': 'Unknown base file: <*>', 'error': 'Invalid format'}
        return {'template_id': 7, 'template': 'Unknown base file: <*>', 'file_path': parts[1]}
    except Exception as e:
        return {'template_id': 7, 'template': 'Unknown base file: <*>', 'error': str(e)}

def is_log_template_8(log_line):
    return "Removable base files:" in log_line

def parse_log_template_8(log_line):
    try:
        parts = log_line.split(': ')
        if len(parts) != 2 or parts[0] != "Removable base files":
            return {'template_id': 8, 'template': 'Removable base files: <*>', 'error': 'Invalid format'}
        return {'template_id': 8, 'template': 'Removable base files: <*>', 'file_path': parts[1]}
    except Exception as e:
        return {'template_id': 8, 'template': 'Removable base files: <*>', 'error': str(e)}

def is_log_template_9(log):
    return "instance:" in log and "VM Started" in log and "(Lifecycle Event)" in log

def parse_log_template_9(log):
    try:
        parts = log.split(" ")
        instance_id = parts[1].split(":")[1]
        return {
            'template_id': 9,
            'template': "[instance: <*>] VM Started (Lifecycle Event)",
            'instance_id': instance_id
        }
    except Exception as e:
        return {
            'template_id': 9,
            'template': "[instance: <*>] VM Started (Lifecycle Event)"
        }

def is_log_template_10(log):
    return "instance:" in log and "VM Paused" in log and "(Lifecycle Event)" in log

def parse_log_template_10(log):
    try:
        parts = log.split(" ")
        instance = parts[1].split(":")[1]
        return {
            'template_id': 10,
            'template': '[instance: <*>] VM Paused (Lifecycle Event)',
            'instance': instance
        }
    except Exception as e:
        return {
            'template_id': 10,
            'template': '[instance: <*>] VM Paused (Lifecycle Event)'
        }

def is_log_template_11(log):
    return "Creating event network-vif-plugged:" in log and " for instance " in log

def parse_log_template_11(log):
    try:
        parts = log.split()
        if len(parts) < 10:
            return {'template_id': '11', 'template': 'network-vif-plugged', 'error': 'Insufficient parts'}
        template_id = '11'
        template = 'network-vif-plugged'
        var1 = parts[3]
        var2 = parts[4]
        var3 = parts[5]
        var4 = parts[6]
        var5 = parts[7]
        var6 = parts[9]
        return {'template_id': template_id, 'template': template, 'var1': var1, 'var2': var2, 'var3': var3, 'var4': var4, 'var5': var5, 'var6': var6}
    except Exception as e:
        return {'template_id': '11', 'template': 'network-vif-plugged', 'error': str(e)}

def is_log_template_12(log):
    return '[instance:' in log and 'Instance spawned successfully.' in log

def parse_log_template_12(log):
    result = {'template_id': 12, 'template': '[instance: <*>] Instance spawned successfully.'}
    try:
        parts = log.split(']')
        if len(parts) < 2:
            return result
        instance_part = parts[0].split(': ')[1]
        result['instance'] = instance_part
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_13(log):
    return '[instance:' in log and 'Took' in log and 'seconds' in log and 'spawn' in log and 'the' in log

def parse_log_template_13(log):
    try:
        parts = log.split(']')
        instance_id = parts[0].split(': ')[1]
        time_parts = parts[1].split(' ')
        time_value = float(time_parts[0])
        time_unit = time_parts[1]
        return {
            'template_id': 13,
            'template': '[instance: <*>] Took <*>.<*> seconds to spawn the instance on the hypervisor.',
            'instance_id': instance_id,
            'time_value': time_value,
            'time_unit': time_unit
        }
    except Exception as e:
        return {
            'template_id': 13,
            'template': '[instance: <*>] Took <*>.<*> seconds to spawn the instance on the hypervisor.'
        }

def is_log_template_14(log):
    return '[instance:' in log and 'Took' in log and 'seconds to build instance.' in log

def parse_log_template_14(log):
    result = {'template_id': '14', 'template': '[instance: <*>] Took <*>.<*> seconds to build instance.'}
    try:
        parts = log.split(']')
        instance_part = parts[0].split(': ')[1]
        time_part = parts[1].split(' ')
        seconds = float(time_part[0])
        result['instance'] = instance_part
        result['time_seconds'] = seconds
    except (IndexError, ValueError):
        pass
    return result

def is_log_template_15(log):
    return "DELETE" in log and "status:" in log and "len:" in log and "time:" in log

def parse_log_template_15(log):
    result = {
        'template_id': '15',
        'template': '<*> "DELETE <*>" status: <*> len: <*> time: <*>.<*>'
    }
    try:
        parts = log.split('"')
        method = parts[1].split()[0]
        path = parts[1].split()[1]
        status = int(parts[3].split(': ')[1])
        length = int(parts[5].split(': ')[1])
        time = float(parts[7].split(': ')[1])
        result.update({
            'method': method,
            'path': path,
            'status': status,
            'length': length,
            'time': time
        })
    except (IndexError, ValueError) as e:
        pass
    return result

def is_log_template_16(log):
    return '[instance:' in log and 'Terminating instance' in log

def parse_log_template_16(log):
    try:
        parts = log.split(']')
        if len(parts) < 2:
            return {'template_id': 16, 'template': 'Terminating instance', 'instance': None}
        instance_part = parts[0].split(': ')[1]
        return {'template_id': 16, 'template': 'Terminating instance', 'instance': instance_part}
    except Exception as e:
        return {'template_id': 16, 'template': 'Terminating instance', 'instance': None}

def is_log_template_17(log):
    return '[instance:' in log and 'Instance destroyed successfully.' in log

def parse_log_template_17(log):
    result = {'template_id': 17, 'template': '[instance: <*>] Instance destroyed successfully.'}
    try:
        parts = log.split('] ')
        if len(parts) != 2:
            return result
        instance_part = parts[0].split(': ')[1]
        result['instance'] = instance_part
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_18(log):
    return '[instance:' in log and 'Deleting instance files' in log

def parse_log_template_18(log):
    result = {
        'template_id': '18',
        'template': '[instance: <*>] Deleting instance files <*>'
    }
    parts = log.split(']')
    if len(parts) != 2:
        return result
    instance_part = parts[0].split('[')[1]
    instance_id = instance_part.split(':')[1].strip()
    file_part = parts[1].split('Deleting instance files')[1].strip()
    result['instance_id'] = instance_id
    result['file_path'] = file_part
    return result

def is_log_template_19(log):
    return '[instance:' in log and 'Deletion of' in log and 'complete' in log

def parse_log_template_19(log):
    try:
        parts = log.split(']')
        instance_part = parts[0].split(': ')[1]
        deletion_part = parts[1].split('Deletion of ')[1].split(' complete')[0]
        return {
            'template_id': 19,
            'template': '[instance: <*>] Deletion of <*> complete',
            'instance': instance_part,
            'deletion_path': deletion_part
        }
    except IndexError:
        return {
            'template_id': 19,
            'template': '[instance: <*>] Deletion of <*> complete'
        }

def is_log_template_20(log):
    return '[instance:' in log and 'Took' in log and 'seconds' in log and 'destroy' in log and 'the' in log

def parse_log_template_20(log):
    result = {'template_id': '20', 'template': '[instance: <*>] Took <*>.<*> seconds to destroy the instance on the hypervisor.'}
    try:
        parts = log.split(' ')
        instance_id = parts[1].split(':')[1]
        time_taken = parts[3] + '.' + parts[4]
        result['instance_id'] = instance_id
        result['time_taken'] = time_taken
    except IndexError:
        pass
    return result

def is_log_template_21(log):
    return '[instance:' in log and 'Took' in log and 'seconds' in log and 'deallocate network for instance.' in log

def parse_log_template_21(log):
    result = {
        'template_id': '21',
        'template': '[instance: <*>] Took <*>.<*> seconds to deallocate network for instance.'
    }
    try:
        parts = log.split(']')
        instance_part = parts[0].split(': ')[1]
        time_part = parts[1].split(' ')[1]
        result['instance'] = instance_part
        result['time'] = time_part
    except IndexError:
        pass
    return result

def is_log_template_22(log):
    return "Removing base or swap file:" in log

def parse_log_template_22(log):
    result = {'template_id': 22, 'template': 'Removing base or swap file: <*>'}
    try:
        parts = log.split(': ')
        if len(parts) == 2 and parts[0] == 'Removing base or swap file':
            result['file_path'] = parts[1].strip()
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_23(log):
    return "HTTP" in log and "exception thrown:" in log and "No instances found" in log and "for any event" in log

def parse_log_template_23(log):
    try:
        return {
            'template_id': '23',
            'template': 'HTTP exception thrown: No instances found for any event',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': '23',
            'template': 'HTTP exception thrown: No instances found for any event',
            'variables': {}
        }

def is_log_template_24(log):
    return '[instance:' in log and 'Attempting claim:' in log and 'memory' in log and 'MB,' in log and 'disk' in log and 'GB,' in log and 'vcpus' in log and 'CPU' in log

def parse_log_template_24(log):
    result = {
        'template_id': 24,
        'template': '[instance: <*>] Attempting claim: memory <*> MB, disk <*> GB, vcpus <*> CPU'
    }
    try:
        parts = log.split('] ')
        instance = parts[0].split(': ')[1]
        details = parts[1].split(', ')
        memory = details[0].split(' ')[2]
        disk = details[1].split(' ')[2]
        vcpus = details[2].split(' ')[2]
        result['instance'] = instance
        result['memory'] = memory
        result['disk'] = disk
        result['vcpus'] = vcpus
    except (IndexError, ValueError) as e:
        pass
    return result

def process_log(raw_line: str) -> Dict:
    """Master router function"""
    if is_log_template_0(raw_line):
        return parse_log_template_0(raw_line)
    if is_log_template_1(raw_line):
        return parse_log_template_1(raw_line)
    if is_log_template_2(raw_line):
        return parse_log_template_2(raw_line)
    if is_log_template_3(raw_line):
        return parse_log_template_3(raw_line)
    if is_log_template_4(raw_line):
        return parse_log_template_4(raw_line)
    if is_log_template_5(raw_line):
        return parse_log_template_5(raw_line)
    if is_log_template_6(raw_line):
        return parse_log_template_6(raw_line)
    if is_log_template_7(raw_line):
        return parse_log_template_7(raw_line)
    if is_log_template_8(raw_line):
        return parse_log_template_8(raw_line)
    if is_log_template_9(raw_line):
        return parse_log_template_9(raw_line)
    if is_log_template_10(raw_line):
        return parse_log_template_10(raw_line)
    if is_log_template_11(raw_line):
        return parse_log_template_11(raw_line)
    if is_log_template_12(raw_line):
        return parse_log_template_12(raw_line)
    if is_log_template_13(raw_line):
        return parse_log_template_13(raw_line)
    if is_log_template_14(raw_line):
        return parse_log_template_14(raw_line)
    if is_log_template_15(raw_line):
        return parse_log_template_15(raw_line)
    if is_log_template_16(raw_line):
        return parse_log_template_16(raw_line)
    if is_log_template_17(raw_line):
        return parse_log_template_17(raw_line)
    if is_log_template_18(raw_line):
        return parse_log_template_18(raw_line)
    if is_log_template_19(raw_line):
        return parse_log_template_19(raw_line)
    if is_log_template_20(raw_line):
        return parse_log_template_20(raw_line)
    if is_log_template_21(raw_line):
        return parse_log_template_21(raw_line)
    if is_log_template_22(raw_line):
        return parse_log_template_22(raw_line)
    if is_log_template_23(raw_line):
        return parse_log_template_23(raw_line)
    if is_log_template_24(raw_line):
        return parse_log_template_24(raw_line)
    else:
        return {'template_id': -1, 'template': 'UNKNOWN', 'raw': raw_line}
