"""
Parser Bank for HealthApp_2k
Generated by QwenLog
Model: Qwen2.5-Coder-7B
Generated: 2026-01-21 09:54:20
Templates: 25
"""

from typing import Dict, Optional

def is_log_template_0(log):
    return log.startswith('onExtend:')

def parse_log_template_0(log):
    try:
        parts = log.split(':')
        if len(parts) != 2 or not parts[1].isdigit():
            return {'template_id': 0, 'template': 'onExtend:* * * *'}
        timestamp, vars_str = parts[1].split()
        vars_list = vars_str.split()
        if len(vars_list) != 4:
            return {'template_id': 0, 'template': 'onExtend:* * * *'}
        return {
            'template_id': 0,
            'template': 'onExtend:* * * *',
            'var1': int(vars_list[0]),
            'var2': int(vars_list[1]),
            'var3': int(vars_list[2]),
            'var4': int(vars_list[3])
        }
    except Exception as e:
        return {'template_id': 0, 'template': 'onExtend:* * * *'}

def is_log_template_1(log):
    return "onStandStepChanged" in log

def parse_log_template_1(log):
    try:
        parts = log.split()
        if len(parts) != 2 or parts[0] != "onStandStepChanged":
            return {'template_id': 1, 'template': 'onStandStepChanged <*>'}
        return {'template_id': 1, 'template': 'onStandStepChanged <*>', 'variable1': int(parts[1])}
    except Exception as e:
        return {'template_id': 1, 'template': 'onStandStepChanged <*>'}

def is_log_template_2(log):
    return "getTodayTotalDetailSteps =" in log

def parse_log_template_2(log):
    try:
        if not is_log_template_2(log):
            return {'template_id': 'getTodayTotalDetailSteps', 'template': 'getTodayTotalDetailSteps = <*>##<*>##<*>##<*>##<*>##<*>'}
        
        parts = log.split('##')
        if len(parts) != 7:
            return {'template_id': 'getTodayTotalDetailSteps', 'template': 'getTodayTotalDetailSteps = <*>##<*>##<*>##<*>##<*>##<*>'}
        
        template_id = 'getTodayTotalDetailSteps'
        template = 'getTodayTotalDetailSteps = <*>##<*>##<*>##<*>##<*>##<*>'
        variables = {
            'var1': parts[1],
            'var2': parts[2],
            'var3': parts[3],
            'var4': parts[4],
            'var5': parts[5],
            'var6': parts[6]
        }
        
        return {'template_id': template_id, 'template': template, **variables}
    
    except Exception as e:
        return {'template_id': 'getTodayTotalDetailSteps', 'template': 'getTodayTotalDetailSteps = <*>##<*>##<*>##<*>##<*>##<*>'}

def is_log_template_3(log):
    return "setTodayTotalDetailSteps=" in log

def parse_log_template_3(log):
    try:
        parts = log.split("=")[1].split("##")
        template_id = parts[0]
        template = "setTodayTotalDetailSteps=" + template_id
        variable = int(parts[1])
        return {
            'template_id': template_id,
            'template': template,
            'variable': variable
        }
    except (IndexError, ValueError):
        return {
            'template_id': None,
            'template': None,
            'variable': None
        }

def is_log_template_4(log):
    return "calculateCaloriesWithCache" in log

def parse_log_template_4(log):
    try:
        parts = log.split()
        if len(parts) < 2 or parts[0] != "calculateCaloriesWithCache":
            return {'template_id': 4, 'template': 'calculateCaloriesWithCache totalCalories=<*>'}
        total_calories = int(parts[1].split('=')[1])
        return {'template_id': 4, 'template': 'calculateCaloriesWithCache totalCalories=<*>', 'totalCalories': total_calories}
    except (ValueError, IndexError):
        return {'template_id': 4, 'template': 'calculateCaloriesWithCache totalCalories=<*>'}

def is_log_template_5(log):
    return "calculateAltitudeWithCache" in log

def parse_log_template_5(log):
    try:
        parts = log.split()
        if len(parts) < 2 or parts[0] != "calculateAltitudeWithCache":
            return {'template_id': 5, 'template': 'calculateAltitudeWithCache totalAltitude=*'}
        total_altitude = parts[1].split('=')[1]
        return {'template_id': 5, 'template': 'calculateAltitudeWithCache totalAltitude=*', 'totalAltitude': total_altitude}
    except Exception as e:
        return {'template_id': 5, 'template': 'calculateAltitudeWithCache totalAltitude=*'}

def is_log_template_6(log):
    return "processHandleBroadcastAction" in log and "action:android.intent.action.TIME_TICK" in log

def parse_log_template_6(log):
    result = {
        'template_id': 6,
        'template': 'processHandleBroadcastAction action:android.intent.action.TIME_TICK',
        'variables': {}
    }
    if not is_log_template_6(log):
        return result
    return result

def is_log_template_7(log):
    return "REPORT :" in log

def parse_log_template_7(log):
    result = {'template_id': 'template_7', 'template': 'REPORT : <*> <*> <*> <*>'}
    if not is_log_template_7(log):
        return result
    
    parts = log.split()
    if len(parts) != 6:
        return result
    
    try:
        result['var1'] = int(parts[2])
        result['var2'] = int(parts[3])
        result['var3'] = int(parts[4])
        result['var4'] = int(parts[5])
    except ValueError:
        return result
    
    return result

def is_log_template_8(log):
    return "onReceive" in log and "action:" in log and "android.intent.action.SCREEN_ON" in log

def parse_log_template_8(log):
    try:
        return {
            'template_id': 8,
            'template': 'onReceive action: android.intent.action.SCREEN_ON',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 8,
            'template': 'onReceive action: android.intent.action.SCREEN_ON',
            'variables': {}
        }

def is_log_template_9(log):
    return "processHandleBroadcastAction" in log and "action:android.intent.action.SCREEN_ON" in log

def parse_log_template_9(log):
    try:
        return {
            'template_id': 9,
            'template': 'processHandleBroadcastAction action:android.intent.action.SCREEN_ON',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 9,
            'template': 'processHandleBroadcastAction action:android.intent.action.SCREEN_ON',
            'variables': {}
        }

def is_log_template_10(log):
    return "flush" in log and "sensor" in log and "data" in log

def parse_log_template_10(log):
    try:
        return {
            'template_id': 10,
            'template': 'flush sensor data',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 10,
            'template': 'flush sensor data',
            'variables': {}
        }

def is_log_template_11(log):
    return "onReceive action: android.intent.action.SCREEN_OFF" in log

def parse_log_template_11(log):
    try:
        return {
            'template_id': 11,
            'template': 'onReceive action: android.intent.action.SCREEN_OFF',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 11,
            'template': 'onReceive action: android.intent.action.SCREEN_OFF',
            'variables': {}
        }

def is_log_template_12(log):
    return "new date =" in log and "type=" in log

def parse_log_template_12(log):
    result = {
        'template_id': 'template_12',
        'template': 'new date =<*>, type=<*>,<*>.<*>,old=<*>.<*>'
    }
    parts = log.split(',')
    if len(parts) != 3:
        return result
    
    date_part = parts[0].split('=')[1]
    type_part = parts[1].split('=')[1]
    old_part = parts[2].split('=')[1]
    
    try:
        date = int(date_part)
        type1, type2 = map(float, type_part.split(','))
        old1, old2 = map(float, old_part.split(','))
        
        result.update({
            'date': date,
            'type1': type1,
            'type2': type2,
            'old1': old1,
            'old2': old2
        })
    except ValueError:
        pass
    
    return result

def is_log_template_13(log):
    return "getBinderPackageName" in log and "packageName =" in log and "com.huawei.health" in log

def parse_log_template_13(log):
    try:
        if not is_log_template_13(log):
            return {'template_id': 13, 'template': 'getBinderPackageName packageName = com.huawei.health'}
        return {'template_id': 13, 'template': 'getBinderPackageName packageName = com.huawei.health'}
    except Exception as e:
        return {'template_id': 13, 'template': 'getBinderPackageName packageName = com.huawei.health'}

def is_log_template_14(log):
    return "getTodaySportData" in log

def parse_log_template_14(log):
    try:
        parts = log.split()
        if len(parts) < 3 or parts[0] != "getTodaySportData":
            return {'template_id': 14, 'template': 'getTodaySportData mStepsRecordManager=*'}
        return {'template_id': 14, 'template': 'getTodaySportData mStepsRecordManager=*', 'mStepsRecordManager': parts[2]}
    except Exception as e:
        return {'template_id': 14, 'template': 'getTodaySportData mStepsRecordManager=*'}

def is_log_template_15(log):
    return "upLoadOneMinuteDataToEngine" in log

def parse_log_template_15(log):
    if not is_log_template_15(log):
        return {'template_id': '15', 'template': 'upLoadOneMinuteDataToEngine time=<*>,<*>,<*>,<*>,<*>', 'variables': {}}
    
    parts = log.split()
    if len(parts) != 2:
        return {'template_id': '15', 'template': 'upLoadOneMinuteDataToEngine time=<*>,<*>,<*>,<*>,<*>', 'variables': {}}
    
    _, time_values = parts
    values = time_values.split(',')
    if len(values) != 5:
        return {'template_id': '15', 'template': 'upLoadOneMinuteDataToEngine time=<*>,<*>,<*>,<*>,<*>', 'variables': {}}
    
    return {
        'template_id': '15',
        'template': 'upLoadOneMinuteDataToEngine time=<*>,<*>,<*>,<*>,<*>',
        'variables': {
            'time1': values[0],
            'time2': values[1],
            'time3': values[2],
            'time4': values[3],
            'time5': values[4]
        }
    }

def is_log_template_16(log):
    return "startSync" in log and "hiSyncOption" in log and "who" in log

def parse_log_template_16(log):
    result = {
        'template_id': 16,
        'template': 'startSync hiSyncOption = HiSyncOption{syncAction=<*>, syncMethod=<*>, syncScope=<*>, syncDataType=<*>, syncModel=<*>, pushAction=<*>},app = <*> who = <*>'
    }
    try:
        parts = log.split(',')
        app_part = parts[1].split(' ')
        who_part = parts[2].split(' ')
        result['syncAction'] = int(parts[0].split('=')[1].split(',')[0].split('{')[1].split('=')[1])
        result['syncMethod'] = int(parts[0].split('=')[1].split(',')[1].split('=')[1])
        result['syncScope'] = int(parts[0].split('=')[1].split(',')[2].split('=')[1])
        result['syncDataType'] = int(parts[0].split('=')[1].split(',')[3].split('=')[1])
        result['syncModel'] = int(parts[0].split('=')[1].split(',')[4].split('=')[1])
        result['pushAction'] = int(parts[0].split('=')[1].split(',')[5].split('=')[1])
        result['app'] = int(app_part[1])
        result['who'] = int(who_part[1])
    except (IndexError, ValueError) as e:
        pass
    return result

def is_log_template_17(log):
    return "needAutoSync" in log and "autoSyncSwitch is open" in log

def parse_log_template_17(log):
    try:
        return {
            'template_id': 17,
            'template': 'needAutoSync autoSyncSwitch is open',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 17,
            'template': 'needAutoSync autoSyncSwitch is open',
            'variables': {},
            'error': str(e)
        }

def is_log_template_18(log):
    return "initDataPrivacy" in log and "the dataPrivacy switch is open," in log and "start push health data!" in log

def parse_log_template_18(log):
    try:
        return {
            'template_id': 18,
            'template': 'initDataPrivacy the dataPrivacy switch is open, start push health data!',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 18,
            'template': 'initDataPrivacy the dataPrivacy switch is open, start push health data!',
            'variables': {}
        }

def is_log_template_19(log):
    return "initDataPrivacy the dataPrivacy is true" in log

def parse_log_template_19(log):
    try:
        return {
            'template_id': 19,
            'template': "initDataPrivacy the dataPrivacy is true",
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 19,
            'template': "initDataPrivacy the dataPrivacy is true",
            'variables': {},
            'error': str(e)
        }

def is_log_template_20(log):
    return "initUserPrivacy" in log and "the userPrivacy switch is open," in log and "start push user data!" in log

def parse_log_template_20(log):
    result = {
        'template_id': 20,
        'template': 'initUserPrivacy the userPrivacy switch is open, start push user data!'
    }
    try:
        # No variables to extract
        pass
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_21(log):
    return "initUserPrivacy" in log and "the userPrivacy is true" in log

def parse_log_template_21(log):
    try:
        return {
            'template_id': 21,
            'template': 'initUserPrivacy the userPrivacy is true',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 21,
            'template': 'initUserPrivacy the userPrivacy is true',
            'variables': {}
        }

def is_log_template_22(log):
    return "ifCanSync" in log and "not!" in log and "cloud" in log and "version" in log

def parse_log_template_22(log):
    try:
        return {
            'template_id': '22',
            'template': 'ifCanSync not! no cloud version',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': '22',
            'template': 'ifCanSync not! no cloud version',
            'variables': {}
        }

def is_log_template_23(log):
    return "sendSyncFailedBroadcast" in log

def parse_log_template_23(log):
    try:
        return {
            'template_id': 23,
            'template': 'sendSyncFailedBroadcast',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 23,
            'template': 'sendSyncFailedBroadcast',
            'variables': {},
            'error': str(e)
        }

def is_log_template_24(log):
    return "timeStamp" in log and "extendReportTimeStamp=" in log

def parse_log_template_24(log):
    result = {
        'template_id': 24,
        'template': 'timeStamp back,extendReportTimeStamp=<*>'
    }
    try:
        parts = log.split(',')
        for part in parts:
            if "extendReportTimeStamp=" in part:
                result['extendReportTimeStamp'] = int(part.split('=')[1].strip())
                break
    except Exception as e:
        pass
    return result

def process_log(raw_line: str) -> Dict:
    """Master router function"""
    if is_log_template_0(raw_line):
        return parse_log_template_0(raw_line)
    if is_log_template_1(raw_line):
        return parse_log_template_1(raw_line)
    if is_log_template_2(raw_line):
        return parse_log_template_2(raw_line)
    if is_log_template_3(raw_line):
        return parse_log_template_3(raw_line)
    if is_log_template_4(raw_line):
        return parse_log_template_4(raw_line)
    if is_log_template_5(raw_line):
        return parse_log_template_5(raw_line)
    if is_log_template_6(raw_line):
        return parse_log_template_6(raw_line)
    if is_log_template_7(raw_line):
        return parse_log_template_7(raw_line)
    if is_log_template_8(raw_line):
        return parse_log_template_8(raw_line)
    if is_log_template_9(raw_line):
        return parse_log_template_9(raw_line)
    if is_log_template_10(raw_line):
        return parse_log_template_10(raw_line)
    if is_log_template_11(raw_line):
        return parse_log_template_11(raw_line)
    if is_log_template_12(raw_line):
        return parse_log_template_12(raw_line)
    if is_log_template_13(raw_line):
        return parse_log_template_13(raw_line)
    if is_log_template_14(raw_line):
        return parse_log_template_14(raw_line)
    if is_log_template_15(raw_line):
        return parse_log_template_15(raw_line)
    if is_log_template_16(raw_line):
        return parse_log_template_16(raw_line)
    if is_log_template_17(raw_line):
        return parse_log_template_17(raw_line)
    if is_log_template_18(raw_line):
        return parse_log_template_18(raw_line)
    if is_log_template_19(raw_line):
        return parse_log_template_19(raw_line)
    if is_log_template_20(raw_line):
        return parse_log_template_20(raw_line)
    if is_log_template_21(raw_line):
        return parse_log_template_21(raw_line)
    if is_log_template_22(raw_line):
        return parse_log_template_22(raw_line)
    if is_log_template_23(raw_line):
        return parse_log_template_23(raw_line)
    if is_log_template_24(raw_line):
        return parse_log_template_24(raw_line)
    else:
        return {'template_id': -1, 'template': 'UNKNOWN', 'raw': raw_line}
