"""
Parser Bank for HDFS_2k
Generated by QwenLog
Model: Qwen2.5-Coder-7B
Generated: 2026-01-21 06:33:55
Templates: 14
"""

from typing import Dict, Optional

def is_log_template_0(log):
    return "BLOCK*" in log and "NameSystem.addStoredBlock:" in log and "blockMap updated:" in log and "added" in log

def parse_log_template_0(log):
    result = {
        'template_id': 0,
        'template': 'BLOCK* NameSystem.addStoredBlock: blockMap updated: <*>:<*> is added to blk_<*> size <*>'
    }
    try:
        parts = log.split()
        ip_port = parts[3]
        block_id = parts[6]
        block_size = parts[8]
        result['ip_port'] = ip_port
        result['block_id'] = block_id
        result['block_size'] = block_size
    except IndexError:
        pass
    return result

def is_log_template_1(log):
    return "PacketResponder" in log and "for block" in log and "terminating" in log

def parse_log_template_1(log):
    try:
        parts = log.split()
        if len(parts) >= 5 and parts[0] == "PacketResponder" and parts[3] == "for" and parts[4].startswith("block") and parts[-1] == "terminating":
            return {
                'template_id': 1,
                'template': 'PacketResponder <*> for block blk_<*> terminating',
                'var1': parts[1],
                'var2': parts[4][5:]
            }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 1,
        'template': 'PacketResponder <*> for block blk_<*> terminating'
    }

def is_log_template_2(log):
    return "Received block" in log and "of size" in log and "from /" in log

def parse_log_template_2(log):
    try:
        parts = log.split()
        if len(parts) < 7:
            return {'template_id': 2, 'template': 'Received block blk_* of size * from /*'}
        block_id = parts[3].split('_')[1]
        size = parts[5]
        ip = parts[-1]
        return {'template_id': 2, 'template': 'Received block blk_* of size * from /*', 'block_id': block_id, 'size': size, 'ip': ip}
    except Exception as e:
        return {'template_id': 2, 'template': 'Received block blk_* of size * from /*'}

def is_log_template_3(log):
    return "Receiving block" in log and "src:" in log and "dest:" in log

def parse_log_template_3(log):
    result = {
        'template_id': 3,
        'template': 'Receiving block blk_<*> src: /<*>:<*> dest: /<*>:<*>',
        'blk_id': None,
        'src_ip': None,
        'src_port': None,
        'dest_ip': None,
        'dest_port': None
    }
    try:
        parts = log.split()
        if len(parts) >= 7:
            result['blk_id'] = parts[3].split('_')[1]
            result['src_ip'], result['src_port'] = parts[5].split(':')
            result['dest_ip'], result['dest_port'] = parts[7].split(':')
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_4(log):
    return "Deleting block" in log and "file" in log

def parse_log_template_4(log):
    try:
        parts = log.split()
        if len(parts) < 6:
            return {'template_id': 4, 'template': 'Deleting block blk_<*> file /<*>/blk_<*>', 'error': 'Invalid log format'}
        block_id = parts[3].split('_')[1]
        file_path = parts[5]
        return {'template_id': 4, 'template': 'Deleting block blk_<*> file /<*>/blk_<*>', 'block_id': block_id, 'file_path': file_path}
    except Exception as e:
        return {'template_id': 4, 'template': 'Deleting block blk_<*> file /<*>/blk_<*>', 'error': str(e)}

def is_log_template_5(log):
    return "BLOCK*" in log and "NameSystem.delete:" in log and "added to invalidSet" in log

def parse_log_template_5(log):
    result = {
        'template_id': 5,
        'template': 'BLOCK* NameSystem.delete: blk_<*> is added to invalidSet of <*>:<*>'
    }
    parts = log.split()
    if len(parts) >= 8:
        result['blk_id'] = parts[4].split('_')[1]
        result['ip'] = parts[7].split(':')[0]
        result['port'] = parts[7].split(':')[1]
    return result

def is_log_template_6(log):
    return "BLOCK*" in log and "NameSystem.allocateBlock:" in log

def parse_log_template_6(log):
    result = {
        'template_id': 6,
        'template': 'BLOCK* NameSystem.allocateBlock: /<*>/part-<*>. blk_<*>'
    }
    if not is_log_template_6(log):
        return result
    
    parts = log.split('/')
    if len(parts) < 4:
        return result
    
    part_name = parts[-2]
    block_id = parts[-1].split('.')[0].split('blk_')[1]
    
    result['part_name'] = part_name
    result['block_id'] = block_id
    return result

def is_log_template_7(log):
    return "Served block" in log

def parse_log_template_7(log):
    result = {
        'template_id': 7,
        'template': '<*>:<*> Served block blk_<*> to /<*>'
    }
    parts = log.split()
    if len(parts) < 5:
        return result
    ip_port = parts[0]
    block_info = parts[2]
    client_ip = parts[-1]
    result['ip_port'] = ip_port
    result['block_hash'] = block_info.split('_')[-1]
    result['client_ip'] = client_ip
    return result

def is_log_template_8(log):
    return "exception" in log and "while" in log and "serving" in log

def parse_log_template_8(log):
    try:
        parts = log.split(':')
        if len(parts) != 4:
            return {'template_id': '8', 'template': 'blk_<*> to /<*>', 'error': 'Invalid format'}
        ip_port, _, message, _ = parts
        block_id, client_ip = message.split('blk_')[1].split(' to /')
        return {
            'template_id': '8',
            'template': 'blk_<*> to /<*>',
            'ip_port': ip_port,
            'block_id': block_id,
            'client_ip': client_ip
        }
    except Exception as e:
        return {'template_id': '8', 'template': 'blk_<*> to /<*>', 'error': str(e)}

def is_log_template_9(log):
    return "Verification succeeded for blk_" in log

def parse_log_template_9(log):
    try:
        parts = log.split(" ")
        if len(parts) >= 4 and parts[0] == "Verification" and parts[1] == "succeeded" and parts[2] == "for":
            return {
                'template_id': 9,
                'template': 'Verification succeeded for blk_<*>',
                'blk': parts[3]
            }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 9,
        'template': 'Verification succeeded for blk_<*>'
    }

def is_log_template_11(log):
    return "Received block" in log and "src:" in log and "dest:" in log and "of size" in log

def parse_log_template_11(log):
    try:
        parts = log.split()
        template_id = 11
        template = "Received block blk_<*> src: /<*>:<*> dest: /<*>:<*> of size <*>"
        blk_index = parts.index("blk_") + 1
        src_index = parts.index("src:") + 1
        dest_index = parts.index("dest:") + 1
        size_index = parts.index("of") + 1
        
        blk_value = parts[blk_index]
        src_value = parts[src_index].split(':')[1] + ':' + parts[src_index + 1].split(':')[0]
        dest_value = parts[dest_index].split(':')[1] + ':' + parts[dest_index + 1].split(':')[0]
        size_value = parts[size_index + 1]
        
        return {
            'template_id': template_id,
            'template': template,
            'blk': blk_value,
            'src': src_value,
            'dest': dest_value,
            'size': size_value
        }
    except Exception as e:
        return {
            'template_id': template_id,
            'template': template,
            'error': str(e)
        }

def is_log_template_12(log):
    return "Starting thread to transfer block" in log

def parse_log_template_12(log):
    try:
        parts = log.split()
        if len(parts) < 7:
            return {'template_id': 12, 'template': ' <*>:<*> Starting thread to transfer block blk_<*> to <*>:<*>', 'error': 'Insufficient parts'}
        ip1, port1 = parts[0].split(':')
        ip2, port2 = parts[-1].split(':')
        block_id = parts[5].split('_')[1]
        return {'template_id': 12, 'template': ' <*>:<*> Starting thread to transfer block blk_<*> to <*>:<*>', 'ip1': ip1, 'port1': port1, 'block_id': block_id, 'ip2': ip2, 'port2': port2}
    except Exception as e:
        return {'template_id': 12, 'template': ' <*>:<*> Starting thread to transfer block blk_<*> to <*>:<*>', 'error': str(e)}

def is_log_template_13(log):
    return "BLOCK*" in log and "ask" in log and "replicate" in log and "datanode(s)" in log

def parse_log_template_13(log):
    result = {
        'template_id': 'template_13',
        'template': 'BLOCK* ask <*>:<*> to replicate blk_<*> to datanode(s) <*>:<*>'
    }
    try:
        parts = log.split()
        if len(parts) >= 10:
            result['var1'] = parts[2]
            result['var2'] = parts[4]
            result['var3'] = parts[6][3:]
            result['var4'] = parts[8]
            result['var5'] = parts[10][:-1]
        else:
            raise ValueError("Log does not contain enough parts")
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def process_log(raw_line: str) -> Dict:
    """Master router function"""
    if is_log_template_0(raw_line):
        return parse_log_template_0(raw_line)
    if is_log_template_1(raw_line):
        return parse_log_template_1(raw_line)
    if is_log_template_2(raw_line):
        return parse_log_template_2(raw_line)
    if is_log_template_3(raw_line):
        return parse_log_template_3(raw_line)
    if is_log_template_4(raw_line):
        return parse_log_template_4(raw_line)
    if is_log_template_5(raw_line):
        return parse_log_template_5(raw_line)
    if is_log_template_6(raw_line):
        return parse_log_template_6(raw_line)
    if is_log_template_7(raw_line):
        return parse_log_template_7(raw_line)
    if is_log_template_8(raw_line):
        return parse_log_template_8(raw_line)
    if is_log_template_9(raw_line):
        return parse_log_template_9(raw_line)
    if is_log_template_11(raw_line):
        return parse_log_template_11(raw_line)
    if is_log_template_12(raw_line):
        return parse_log_template_12(raw_line)
    if is_log_template_13(raw_line):
        return parse_log_template_13(raw_line)
    else:
        return {'template_id': -1, 'template': 'UNKNOWN', 'raw': raw_line}
