"""
Parser Bank for Thunderbird_2k
Generated by QwenLog
Model: Qwen2.5-Coder-7B
Generated: 2026-01-21 16:54:26
Templates: 25
"""

from typing import Dict, Optional

def is_log_template_0(log):
    return "data_thread()" in log and "got not answer" in log and "from any" in log and "[" in log and "]" in log

def parse_log_template_0(log):
    try:
        parts = log.split(" ")
        for part in parts:
            if "[" in part and "]" in part:
                variable = part.strip("[]")
                return {
                    'template_id': 0,
                    'template': 'data_thread() got not answer from any [Thunderbird_<*>] datasource',
                    'Thunderbird_version': variable
                }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 0,
        'template': 'data_thread() got not answer from any [Thunderbird_<*>] datasource'
    }

def is_log_template_1(log):
    return "synchronized to" in log and "stratum" in log

def parse_log_template_1(log):
    try:
        parts = log.split(',')
        ip = parts[0].split()[-1]
        stratum = parts[1].split()[-1]
        return {
            'template_id': 1,
            'template': 'synchronized to <*>, stratum <*>',
            'ip': ip,
            'stratum': stratum
        }
    except Exception as e:
        return {
            'template_id': 1,
            'template': 'synchronized to <*>, stratum <*>',
            'error': str(e)
        }

def is_log_template_2(log):
    return '[ib_sm_sweep.c:1831]:' in log and 'NEW SWEEP' in log

def parse_log_template_2(log):
    try:
        return {
            'template_id': 'template_2',
            'template': '[ib_sm_sweep.c:1831]: ********************** NEW SWEEP ********************',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 'template_2',
            'template': '[ib_sm_sweep.c:1831]: ********************** NEW SWEEP ********************',
            'variables': {}
        }

def is_log_template_3(log):
    return '[ib_sm_sweep.c:1455]:' in log and 'topology' in log and 'change' in log

def parse_log_template_3(log):
    try:
        return {
            'template_id': 3,
            'template': '[ib_sm_sweep.c:1455]: No topology change',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 3,
            'template': '[ib_sm_sweep.c:1455]: No topology change',
            'variables': {}
        }

def is_log_template_4(log):
    return "[ib_sm_sweep.c:1482]:" in log and "No configuration change required" in log

def parse_log_template_4(log):
    try:
        return {
            'template_id': 4,
            'template': '[ib_sm_sweep.c:1482]: No configuration change required',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 4,
            'template': '[ib_sm_sweep.c:1482]: No configuration change required',
            'variables': {}
        }

def is_log_template_5(log):
    return "Warning:" in log and "failed to resolve data source name" in log

def parse_log_template_5(log):
    result = {'template_id': 5, 'template': 'Warning: we failed to resolve data source name <*>'}
    if not is_log_template_5(log):
        return result
    
    try:
        parts = log.split('name ')
        if len(parts) != 2:
            return result
        
        variable = parts[1].strip()
        result['variable'] = variable
    except Exception as e:
        print(f"Error parsing log: {e}")
    
    return result

def is_log_template_6(log):
    return "session" in log and "closed" in log and "for" in log and "user" in log and "root" in log

def parse_log_template_6(log):
    try:
        return {
            'template_id': 6,
            'template': 'session closed for user root',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 6,
            'template': 'session closed for user root',
            'variables': {}
        }

def is_log_template_7(log):
    return "session opened for user root by" in log

def parse_log_template_7(log):
    try:
        return {
            'template_id': 7,
            'template': 'session opened for user root by',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 7,
            'template': 'session opened for user root by',
            'variables': {}
        }

def is_log_template_8(log):
    return "Reading included configuration file:" in log

def parse_log_template_8(log):
    result = {
        'template_id': 8,
        'template': 'Reading included configuration file: <*> [file=<*>] [line=<*>]',
        'variables': {}
    }
    if not is_log_template_8(log):
        return result
    
    parts = log.split()
    for part in parts:
        if part.startswith('file='):
            result['variables']['file'] = part[5:]
        elif part.startswith('line='):
            result['variables']['line'] = part[5:]
    
    return result

def is_log_template_9(log):
    return "removing" in log

def parse_log_template_9(log):
    try:
        parts = log.split()
        if len(parts) == 2 and parts[0] == "removing":
            return {
                'template_id': 9,
                'template': 'removing <*>',
                'variable': parts[1]
            }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 9,
        'template': 'removing <*>',
        'variable': None
    }

def is_log_template_10(log):
    return "DHCPDISCOVER" in log and "from" in log and "via eth1:" in log and "network" in log

def parse_log_template_10(log):
    try:
        parts = log.split()
        if len(parts) < 6:
            return {'template_id': 'template_10', 'template': 'DHCPDISCOVER from <*> via eth1: network A_net: no free leases'}
        mac_address = parts[3]
        return {'template_id': 'template_10', 'template': 'DHCPDISCOVER from <*> via eth1: network A_net: no free leases', 'mac_address': mac_address}
    except Exception as e:
        return {'template_id': 'template_10', 'template': 'DHCPDISCOVER from <*> via eth1: network A_net: no free leases'}

def is_log_template_11(log):
    return "(root) CMD (run-parts /etc/cron.hourly)" in log

def parse_log_template_11(log):
    try:
        return {
            'template_id': 11,
            'template': "(root) CMD (run-parts /etc/cron.hourly)",
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 11,
            'template': "(root) CMD (run-parts /etc/cron.hourly)",
            'variables': {},
            'error': str(e)
        }

def is_log_template_12(log):
    return "RRD_update" in log and "illegal attempt to update using time" in log

def parse_log_template_12(log):
    result = {'template_id': 12, 'template': 'RRD_update (/var/lib/ganglia/rrds/<*>.rrd): illegal attempt to update using time <*> when last update time is <*> (minimum one second step)'}
    try:
        parts = log.split(':')
        if len(parts) < 2:
            return result
        message = parts[1].strip()
        if "illegal attempt to update using time" not in message:
            return result
        time_parts = message.split('when last update time is ')
        if len(time_parts) != 2:
            return result
        update_time = time_parts[0].split('using time ')[1]
        last_update_time = time_parts[1].split(' (')[0]
        result['update_time'] = update_time
        result['last_update_time'] = last_update_time
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_13(log):
    return "PCI interrupt" in log and "GSI" in log and "(level, low)" in log and "-> IRQ" in log

def parse_log_template_13(log):
    try:
        parts = log.split(" -> ")
        pci_interrupt = parts[0].split("PCI interrupt ")[1]
        gsi = parts[1].split("GSI ")[1].split(" (level, low)")[0]
        irq = parts[2].split("IRQ ")[1]
        return {
            'template_id': 13,
            'template': 'PCI interrupt <*> -> GSI <*> (level, low) -> IRQ <*>',
            'pci_interrupt': pci_interrupt,
            'gsi': gsi,
            'irq': irq
        }
    except (IndexError, ValueError):
        return {
            'template_id': 13,
            'template': 'PCI interrupt <*> -> GSI <*> (level, low) -> IRQ <*>'
        }

def is_log_template_14(log):
    return "unable to qualify my own domain name" in log and "using short name" in log

def parse_log_template_14(log):
    result = {'template_id': 14, 'template': 'unable to qualify my own domain name (<*>) -- using short name'}
    if not is_log_template_14(log):
        return result
    
    try:
        parts = log.split('(')[1].split(')')[0]
        result['variable'] = parts.strip()
    except IndexError:
        pass
    
    return result

def is_log_template_15(log):
    return "from=root," in log

def parse_log_template_15(log):
    result = {
        'template_id': '15',
        'template': '<*>: from=root, size=<*>, class=<*>, nrcpts=<*>, msgid=<<*>>, relay=#<*>#@localhost'
    }
    try:
        parts = log.split(': from=root, size=')
        if len(parts) != 2:
            return result
        size_part, rest = parts[1].split(', class=')
        class_part, nrcpts_part = rest.split(', nrcpts=')
        nrcpts_msgid_part, relay_part = nrcpts_part.split(', msgid=')
        msgid_relay_part, relay_end = relay_part.split(' relay=')
        relay_host_part, host_end = relay_end.split('@localhost')
        result['size'] = size_part.strip()
        result['class'] = class_part.strip()
        result['nrcpts'] = nrcpts_part.strip()
        result['msgid'] = nrcpts_msgid_part.strip()
        result['relay'] = relay_host_part.strip()
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_16(log):
    return "to=root," in log and "ctladdr=root" in log and "(0/0)" in log and "mailer=relay," in log and "stat=Deferred:" in log

def parse_log_template_16(log):
    result = {
        'template_id': 'template_16',
        'template': '<*>: to=root, ctladdr=root (0/0), delay=<*>:<*>:<*>, xdelay=<*>:<*>:<*>, mailer=relay, pri=<*>, relay=[<*>] [<*>], dsn=<*>.<*>.<*>, stat=Deferred: Connection refused by [<*>]'
    }
    try:
        parts = log.split(', ')
        for part in parts:
            if 'to=' in part:
                result['to'] = part.split('=')[1].split(',')[0]
            elif 'ctladdr=' in part:
                result['ctladdr'] = part.split('=')[1].split(',')[0]
            elif '(0/0)' in part:
                result['ctladdr'] += part.split(',')[0]
            elif 'delay=' in part:
                result['delay'] = part.split('=')[1].split(':')[0]
                result['xdelay'] = part.split('=')[1].split(':')[1]
                result['xdelay'] = part.split('=')[1].split(':')[2]
            elif 'mailer=' in part:
                result['mailer'] = part.split('=')[1].split(',')[0]
            elif 'pri=' in part:
                result['pri'] = part.split('=')[1].split(',')[0]
            elif 'relay=[' in part:
                result['relay'] = part.split('=')[1].split(']')[0]
                result['relay_ip'] = part.split('=')[1].split(']')[1].strip('[]')
            elif 'dsn=' in part:
                result['dsn'] = part.split('=')[1].split('.')[0]
                result['dsn_code'] = part.split('=')[1].split('.')[1]
                result['dsn_detail'] = part.split('=')[1].split('.')[2]
            elif 'stat=' in part:
                result['stat'] = part.split('=')[1].split(':')[0]
                result['stat_reason'] = part.split('=')[1].split(':')[1].strip()
    except Exception as e:
        print

def is_log_template_17(log):
    return "PCI Interrupt Routing Table" in log

def parse_log_template_17(log):
    try:
        parts = log.split("[")
        if len(parts) > 1:
            variable = parts[1].split("]")[0]
            return {
                'template_id': 17,
                'template': 'PCI Interrupt Routing Table',
                'variable': variable
            }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 17,
        'template': 'PCI Interrupt Routing Table'
    }

def is_log_template_18(log):
    return "DHCPREQUEST for" in log and "from" in log and "via eth1:" in log

def parse_log_template_18(log):
    result = {'template_id': '18', 'template': 'DHCPREQUEST for <*> (<*>) from <*> via eth1: unknown lease <*>.'}
    parts = log.split()
    if len(parts) >= 9:
        result['ip_address'] = parts[4]
        result['subnet_mask'] = parts[6]
        result['mac_address'] = parts[8]
        result['lease_ip'] = parts[10]
    return result

def is_log_template_19(log):
    return "v001" in log and "DELL" in log and "BKC" in log and "MSFT" in log

def parse_log_template_19(log):
    try:
        parts = log.split()
        if len(parts) < 7:
            return {'template_id': None, 'template': None, 'var1': None, 'var2': None, 'var3': None, 'var4': None}
        template_id = parts[0]
        var1 = parts[3]
        var2 = parts[5]
        var3 = parts[6].split('@')[0]
        var4 = parts[6].split('@')[1]
        return {'template_id': template_id, 'template': log, 'var1': var1, 'var2': var2, 'var3': var3, 'var4': var4}
    except Exception as e:
        return {'template_id': None, 'template': None, 'var1': None, 'var2': None, 'var3': None, 'var4': None}

def is_log_template_20(log):
    return "Wait for ready failed before probe !" in log

def parse_log_template_20(log):
    result = {
        'template_id': '20',
        'template': 'Wait for ready failed before probe !'
    }
    return result

def is_log_template_21(log):
    return "DHCPDISCOVER" in log and "from" in log and "via eth1" in log

def parse_log_template_21(log):
    result = {'template_id': 21, 'template': 'DHCPDISCOVER from <*> via eth1'}
    try:
        parts = log.split()
        if len(parts) >= 5 and parts[0] == "DHCPDISCOVER" and parts[2] == "from" and parts[4] == "via" and parts[5] == "eth1":
            result['mac_address'] = parts[3]
        else:
            raise ValueError("Invalid log format")
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_22(log):
    return "DHCPOFFER" in log and "via eth1" in log

def parse_log_template_22(log):
    result = {'template_id': 22, 'template': 'DHCPOFFER on <*> to <*> via eth1'}
    if not is_log_template_22(log):
        return result
    
    parts = log.split()
    if len(parts) < 6:
        return result
    
    try:
        ip_address = parts[3]
        mac_address = parts[5]
        result['ip_address'] = ip_address
        result['mac_address'] = mac_address
    except IndexError:
        pass
    
    return result

def is_log_template_23(log):
    return "(root)" in log and "CMD" in log and "/projects/tbird/temps/get_temps" in log

def parse_log_template_23(log):
    result = {'template_id': '23', 'template': '(root) CMD (/projects/tbird/temps/get_temps <*>)'}
    if not is_log_template_23(log):
        return result
    
    parts = log.split()
    if len(parts) < 6:
        return result
    
    try:
        variable = parts[5].strip('()')
        result['variable'] = variable
    except Exception as e:
        print(f"Error parsing log: {e}")
    
    return result

def is_log_template_24(log):
    return "unqualified host name" in log and "unknown;" in log and "sleeping for retry" in log

def parse_log_template_24(log):
    result = {'template_id': 24, 'template': 'My unqualified host name (<*>) unknown; sleeping for retry'}
    try:
        parts = log.split(' (')
        if len(parts) > 1:
            host_name = parts[1].split(')')[0]
            result['host_name'] = host_name
        else:
            raise ValueError("Invalid log format")
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def process_log(raw_line: str) -> Dict:
    """Master router function"""
    if is_log_template_0(raw_line):
        return parse_log_template_0(raw_line)
    if is_log_template_1(raw_line):
        return parse_log_template_1(raw_line)
    if is_log_template_2(raw_line):
        return parse_log_template_2(raw_line)
    if is_log_template_3(raw_line):
        return parse_log_template_3(raw_line)
    if is_log_template_4(raw_line):
        return parse_log_template_4(raw_line)
    if is_log_template_5(raw_line):
        return parse_log_template_5(raw_line)
    if is_log_template_6(raw_line):
        return parse_log_template_6(raw_line)
    if is_log_template_7(raw_line):
        return parse_log_template_7(raw_line)
    if is_log_template_8(raw_line):
        return parse_log_template_8(raw_line)
    if is_log_template_9(raw_line):
        return parse_log_template_9(raw_line)
    if is_log_template_10(raw_line):
        return parse_log_template_10(raw_line)
    if is_log_template_11(raw_line):
        return parse_log_template_11(raw_line)
    if is_log_template_12(raw_line):
        return parse_log_template_12(raw_line)
    if is_log_template_13(raw_line):
        return parse_log_template_13(raw_line)
    if is_log_template_14(raw_line):
        return parse_log_template_14(raw_line)
    if is_log_template_15(raw_line):
        return parse_log_template_15(raw_line)
    if is_log_template_16(raw_line):
        return parse_log_template_16(raw_line)
    if is_log_template_17(raw_line):
        return parse_log_template_17(raw_line)
    if is_log_template_18(raw_line):
        return parse_log_template_18(raw_line)
    if is_log_template_19(raw_line):
        return parse_log_template_19(raw_line)
    if is_log_template_20(raw_line):
        return parse_log_template_20(raw_line)
    if is_log_template_21(raw_line):
        return parse_log_template_21(raw_line)
    if is_log_template_22(raw_line):
        return parse_log_template_22(raw_line)
    if is_log_template_23(raw_line):
        return parse_log_template_23(raw_line)
    if is_log_template_24(raw_line):
        return parse_log_template_24(raw_line)
    else:
        return {'template_id': -1, 'template': 'UNKNOWN', 'raw': raw_line}
