"""
Parser Bank for HPC_2k
Generated by QwenLog
Model: Qwen2.5-Coder-7B
Generated: 2026-01-21 12:47:47
Templates: 25
"""

from typing import Dict, Optional

def is_log_template_0(log):
    return "Linkerror" in log and "event interval expired" in log

def parse_log_template_0(log):
    try:
        return {
            'template_id': 0,
            'template': 'Linkerror event interval expired',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 0,
            'template': 'Linkerror event interval expired',
            'variables': {}
        }

def is_log_template_1(log):
    return 'ambient=' in log

def parse_log_template_1(log):
    try:
        parts = log.split('=')
        if len(parts) != 2 or parts[0] != 'ambient':
            return {'template_id': 1, 'template': 'ambient=*', 'ambient': None}
        return {'template_id': 1, 'template': 'ambient=*', 'ambient': int(parts[1])}
    except Exception as e:
        return {'template_id': 1, 'template': 'ambient=*', 'ambient': None}

def is_log_template_2(log):
    return "normal" in log

def parse_log_template_2(log):
    try:
        return {
            'template_id': 'normal',
            'template': 'normal',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 'normal',
            'template': 'normal',
            'variables': {}
        }

def is_log_template_3(log):
    return "warning" in log

def parse_log_template_3(log):
    try:
        return {
            'template_id': 3,
            'template': 'warning',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 3,
            'template': 'warning',
            'variables': {},
            'error': str(e)
        }

def is_log_template_4(log):
    return "running" in log

def parse_log_template_4(log):
    try:
        return {
            'template_id': 4,
            'template': 'running',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 4,
            'template': 'running',
            'variables': {},
            'error': str(e)
        }

def is_log_template_5(log):
    return "configured" in log and "out" in log

def parse_log_template_5(log):
    try:
        return {
            'template_id': 5,
            'template': 'configured out',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 5,
            'template': 'configured out',
            'variables': {},
            'error': str(e)
        }

def is_log_template_6(log):
    return "Fan speeds" in log and "****" in log

def parse_log_template_6(log):
    try:
        parts = log.split(" (")[1].split(" )")[0].split()
        if len(parts) != 6:
            return {'template_id': 6, 'template': 'Fan speeds ( <*> <*> <*> **** <*> <*> )'}
        return {
            'template_id': 6,
            'template': 'Fan speeds ( <*> <*> <*> **** <*> <*> )',
            'var1': int(parts[0]),
            'var2': int(parts[1]),
            'var3': int(parts[2]),
            'var4': int(parts[3]),
            'var5': int(parts[4])
        }
    except Exception as e:
        return {'template_id': 6, 'template': 'Fan speeds ( <*> <*> <*> **** <*> <*> )'}

def is_log_template_7(log):
    return "boot" in log and "(command" in log

def parse_log_template_7(log):
    try:
        parts = log.split()
        if len(parts) < 4 or parts[2] != "(command":
            return {'template_id': 7, 'template': 'boot  (command <*>'}
        return {'template_id': 7, 'template': 'boot  (command <*>', 'command': parts[3]}
    except Exception as e:
        return {'template_id': 7, 'template': 'boot  (command <*>'}

def is_log_template_8(log):
    return "wait" in log and "(command" in log

def parse_log_template_8(log):
    try:
        parts = log.split()
        if len(parts) < 4 or parts[1] != "(command":
            return {'template_id': 8, 'template': 'wait  (command <*>)', 'error': 'Invalid format'}
        return {'template_id': 8, 'template': 'wait  (command <*>)', 'command': parts[2]}
    except Exception as e:
        return {'template_id': 8, 'template': 'wait  (command <*>)', 'error': str(e)}

def is_log_template_9(log):
    return "not responding" in log

def parse_log_template_9(log):
    try:
        return {
            'template_id': 9,
            'template': 'not responding',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 9,
            'template': 'not responding',
            'variables': {},
            'error': str(e)
        }

def is_log_template_10(log):
    return "link" in log and "errors" in log and "remain" in log and "current" in log

def parse_log_template_10(log):
    try:
        return {
            'template_id': 10,
            'template': 'link errors remain current',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 10,
            'template': 'link errors remain current',
            'variables': {}
        }

def is_log_template_11(log):
    return "NIFF:" in log and "node" in log and "has detected an available network connection" in log and "via interface ee0" in log

def parse_log_template_11(log):
    result = {
        'template_id': 'template_11',
        'template': 'NIFF: node node-<*> has detected an available network connection on network <*> via interface ee0'
    }
    parts = log.split()
    if len(parts) >= 7:
        node_name = parts[3].split('-')[1]
        network_address = parts[6]
        result['node_name'] = node_name
        result['network_address'] = network_address
    return result

def is_log_template_12(log):
    return "NIFF:" in log and "node" in log and "has detected an available network connection" in log

def parse_log_template_12(log):
    result = {'template_id': 'template_12', 'template': 'NIFF: node node-<*> has detected an available network connection on network <*> via interface alt0'}
    try:
        parts = log.split()
        node_name = parts[parts.index('node') + 1].split('-')[1]
        network_address = parts[parts.index('network') + 1]
        result['node_name'] = node_name
        result['network_address'] = network_address
    except (IndexError, ValueError):
        pass
    return result

def is_log_template_13(log):
    return "ClusterFileSystem:" in log and "ServerFileSystem" in log and "domain" in log and "is no longer served by node" in log

def parse_log_template_13(log):
    result = {'template_id': 13, 'template': 'ClusterFileSystem: ServerFileSystem domain <*> is no longer served by node node-<*>'}
    if not is_log_template_13(log):
        return result
    
    parts = log.split()
    try:
        domain = parts[parts.index('domain') + 1]
        node = parts[parts.index('node') + 1]
        result['domain'] = domain
        result['node'] = node
    except (IndexError, ValueError):
        pass
    
    return result

def is_log_template_14(log):
    return "ClusterFileSystem:" in log and "There is no server for ServerFileSystem" in log

def parse_log_template_14(log):
    result = {'template_id': 14, 'template': 'ClusterFileSystem: There is no server for ServerFileSystem domain storage<*>'}
    if not is_log_template_14(log):
        return result
    
    parts = log.split('domain storage')
    if len(parts) != 2:
        return result
    
    result['variable'] = parts[1].strip()
    return result

def is_log_template_15(log):
    return 'critical' in log

def parse_log_template_15(log):
    try:
        return {
            'template_id': 15,
            'template': 'critical',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 15,
            'template': 'critical',
            'variables': {}
        }

def is_log_template_16(log):
    return "blocked" in log

def parse_log_template_16(log):
    try:
        return {
            'template_id': 16,
            'template': 'blocked',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 16,
            'template': 'blocked',
            'variables': {},
            'error': str(e)
        }

def is_log_template_17(log):
    return "Link" in log and "error" in log

def parse_log_template_17(log):
    try:
        return {
            'template_id': 17,
            'template': 'Link error',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 17,
            'template': 'Link error',
            'variables': {}
        }

def is_log_template_18(log):
    return "Link ok" in log

def parse_log_template_18(log):
    try:
        return {
            'template_id': 18,
            'template': 'Link ok',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 18,
            'template': 'Link ok',
            'variables': {}
        }

def is_log_template_19(log):
    return "Component State Change: Component" in log and "is in the unavailable state (HWID=" in log

def parse_log_template_19(log):
    result = {'template_id': '19', 'template': 'Component State Change: Component <*> is in the unavailable state (HWID=<*>)'}
    try:
        parts = log.split('Component ')
        component = parts[1].split(' is')[0].strip('"')
        hwid = parts[1].split('HWID=')[1].split(')')[0]
        result['component'] = component
        result['hwid'] = hwid
    except (IndexError, ValueError):
        pass
    return result

def is_log_template_20(log):
    return "ServerFileSystem:" in log and "domain" in log and "is full" in log

def parse_log_template_20(log):
    try:
        parts = log.split()
        if len(parts) >= 5 and parts[0] == "ServerFileSystem:" and parts[2] == "domain":
            return {
                'template_id': 20,
                'template': 'ServerFileSystem: ServerFileSystem domain <*> is full',
                'domain': parts[4]
            }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 20,
        'template': 'ServerFileSystem: ServerFileSystem domain <*> is full'
    }

def is_log_template_21(log):
    return "Fan speeds" in log and "(" in log and ")" in log

def parse_log_template_21(log):
    try:
        if not is_log_template_21(log):
            return {'template_id': '21', 'template': 'Fan speeds ( <*> <*> <*> <*> <*> <*> )'}
        
        parts = log.split()
        if len(parts) < 8 or parts[0] != "Fan" or parts[1] != "speeds":
            return {'template_id': '21', 'template': 'Fan speeds ( <*> <*> <*> <*> <*> <*> )'}
        
        values = parts[2:8]
        if len(values) != 6:
            return {'template_id': '21', 'template': 'Fan speeds ( <*> <*> <*> <*> <*> <*> )'}
        
        return {
            'template_id': '21',
            'template': 'Fan speeds ( <*> <*> <*> <*> <*> <*> )',
            'fan_speed1': int(values[0]),
            'fan_speed2': int(values[1]),
            'fan_speed3': int(values[2]),
            'fan_speed4': int(values[3]),
            'fan_speed5': int(values[4]),
            'fan_speed6': int(values[5])
        }
    except Exception as e:
        return {'template_id': '21', 'template': 'Fan speeds ( <*> <*> <*> <*> <*> <*> )'}

def is_log_template_22(log):
    return "Command" in log and "has" in log and "completed" in log and "successfully" in log

def parse_log_template_22(log):
    try:
        return {
            'template_id': '22',
            'template': 'Command has completed successfully',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': '22',
            'template': 'Command has completed successfully',
            'variables': {}
        }

def is_log_template_23(log):
    return "Link in reset" in log

def parse_log_template_23(log):
    try:
        return {
            'template_id': 23,
            'template': 'Link in reset',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 23,
            'template': 'Link in reset',
            'variables': {}
        }

def is_log_template_24(log):
    return "Targeting domains:node-D" in log and "nodes:node-" in log and "child of command" in log

def parse_log_template_24(log):
    result = {
        'template_id': 'template_24',
        'template': 'Targeting domains:node-D<*> and nodes:node-[<*>-<*>] child of command <*>'
    }
    try:
        parts = log.split()
        node_d_index = parts.index('domains:node-D') + 1
        node_range_index = parts.index('nodes:node-') + 1
        command_index = parts.index('child') + 1
        
        node_d = parts[node_d_index]
        node_range = parts[node_range_index]
        command = parts[command_index]
        
        result['node_d'] = node_d
        result['node_range'] = node_range
        result['command'] = command
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def process_log(raw_line: str) -> Dict:
    """Master router function"""
    if is_log_template_0(raw_line):
        return parse_log_template_0(raw_line)
    if is_log_template_1(raw_line):
        return parse_log_template_1(raw_line)
    if is_log_template_2(raw_line):
        return parse_log_template_2(raw_line)
    if is_log_template_3(raw_line):
        return parse_log_template_3(raw_line)
    if is_log_template_4(raw_line):
        return parse_log_template_4(raw_line)
    if is_log_template_5(raw_line):
        return parse_log_template_5(raw_line)
    if is_log_template_6(raw_line):
        return parse_log_template_6(raw_line)
    if is_log_template_7(raw_line):
        return parse_log_template_7(raw_line)
    if is_log_template_8(raw_line):
        return parse_log_template_8(raw_line)
    if is_log_template_9(raw_line):
        return parse_log_template_9(raw_line)
    if is_log_template_10(raw_line):
        return parse_log_template_10(raw_line)
    if is_log_template_11(raw_line):
        return parse_log_template_11(raw_line)
    if is_log_template_12(raw_line):
        return parse_log_template_12(raw_line)
    if is_log_template_13(raw_line):
        return parse_log_template_13(raw_line)
    if is_log_template_14(raw_line):
        return parse_log_template_14(raw_line)
    if is_log_template_15(raw_line):
        return parse_log_template_15(raw_line)
    if is_log_template_16(raw_line):
        return parse_log_template_16(raw_line)
    if is_log_template_17(raw_line):
        return parse_log_template_17(raw_line)
    if is_log_template_18(raw_line):
        return parse_log_template_18(raw_line)
    if is_log_template_19(raw_line):
        return parse_log_template_19(raw_line)
    if is_log_template_20(raw_line):
        return parse_log_template_20(raw_line)
    if is_log_template_21(raw_line):
        return parse_log_template_21(raw_line)
    if is_log_template_22(raw_line):
        return parse_log_template_22(raw_line)
    if is_log_template_23(raw_line):
        return parse_log_template_23(raw_line)
    if is_log_template_24(raw_line):
        return parse_log_template_24(raw_line)
    else:
        return {'template_id': -1, 'template': 'UNKNOWN', 'raw': raw_line}
