"""
Parser Bank for BGL_2k
Generated by QwenLog
Model: Qwen2.5-Coder-7B
Generated: 2026-01-21 00:01:20
Templates: 25
"""

from typing import Dict, Optional

def is_log_template_0(log):
    return "generating" in log

def parse_log_template_0(log):
    try:
        parts = log.split('.')
        if len(parts) == 3 and parts[0] == "generating" and parts[1] == "core":
            return {
                'template_id': 0,
                'template': 'generating core.*',
                'variable': int(parts[2])
            }
    except Exception as e:
        pass
    return {
        'template_id': 0,
        'template': 'generating core.*',
        'variable': None
    }

def is_log_template_1(log):
    return "iar" in log and "dear" in log

def parse_log_template_1(log):
    try:
        parts = log.split()
        if len(parts) != 4 or parts[0] != "iar" or parts[2] != "dear":
            return {'template_id': 1, 'template': 'iar <*> dear <*>'}
        return {
            'template_id': 1,
            'template': 'iar <*> dear <*>',
            'var1': parts[1],
            'var2': parts[3]
        }
    except Exception as e:
        print(f"Error parsing log: {e}")
        return {'template_id': 1, 'template': 'iar <*> dear <*>'}

def is_log_template_2(log):
    return "floating point alignment exceptions" in log

def parse_log_template_2(log):
    try:
        parts = log.split()
        if len(parts) >= 2 and parts[-2] == "floating" and parts[-1] == "point alignment exceptions":
            return {
                'template_id': 2,
                'template': 'floating point alignment exceptions',
                'count': int(parts[0])
            }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 2,
        'template': 'floating point alignment exceptions'
    }

def is_log_template_3(log):
    return "double-hummer alignment exceptions" in log

def parse_log_template_3(log):
    try:
        parts = log.split()
        if len(parts) >= 3 and parts[1] == "double-hummer" and parts[2] == "alignment" and parts[3] == "exceptions":
            return {
                'template_id': 3,
                'template': 'double-hummer alignment exceptions',
                'variable': parts[0]
            }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 3,
        'template': 'double-hummer alignment exceptions',
        'variable': None
    }

def is_log_template_4(log):
    return "CE sym" in log and "mask" in log

def parse_log_template_4(log):
    result = {'template_id': 4, 'template': 'CE sym <*>, at <*>, mask <*>'}
    try:
        parts = log.split(', ')
        sym = int(parts[1].split(' ')[1])
        at = parts[2].split(' ')[1]
        mask = int(parts[3].split(' ')[1], 16)
        result.update({'sym': sym, 'at': at, 'mask': mask})
    except (IndexError, ValueError) as e:
        pass
    return result

def is_log_template_5(log):
    return "total interrupts" in log and "critical input interrupts" in log

def parse_log_template_5(log):
    try:
        parts = log.split()
        total_interrupts = int(parts[0])
        critical_input_interrupts = int(parts[3])
        total_microseconds_critical = int(parts[6].replace(',', ''))
        max_microseconds_critical = int(parts[9].replace(',', ''))
        return {
            'template_id': 5,
            'template': "<*> total interrupts. 0 critical input interrupts. <*> microseconds total spent on critical input interrupts, <*> microseconds max time in a critical input interrupt.",
            'total_interrupts': total_interrupts,
            'critical_input_interrupts': critical_input_interrupts,
            'total_microseconds_critical': total_microseconds_critical,
            'max_microseconds_critical': max_microseconds_critical
        }
    except (IndexError, ValueError) as e:
        return {
            'template_id': 5,
            'template': "<*> total interrupts. 0 critical input interrupts. <*> microseconds total spent on critical input interrupts, <*> microseconds max time in a critical input interrupt."
        }

def is_log_template_6(log):
    return "data" in log and "TLB" in log and "error" in log and "interrupt" in log

def parse_log_template_6(log):
    try:
        return {
            'template_id': 6,
            'template': 'data TLB error interrupt',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 6,
            'template': 'data TLB error interrupt',
            'variables': {}
        }

def is_log_template_7(log):
    return "microseconds spent in the rbs signal handler during" in log and "microseconds was the maximum time for a single instance of a correctable ddr." in log

def parse_log_template_7(log):
    result = {
        'template_id': 7,
        'template': ' <*> microseconds spent in the rbs signal handler during <*> calls. <*> microseconds was the maximum time for a single instance of a correctable ddr.'
    }
    try:
        parts = log.split(' microseconds spent in the rbs signal handler during ')
        if len(parts) != 2:
            return result
        calls_part, max_time_part = parts[1].split(' microseconds was the maximum time for a single instance of a correctable ddr.')
        if len(calls_part.split()) != 2 or len(max_time_part.split()) != 1:
            return result
        result['variable_1'], result['variable_2'] = calls_part.split()
        result['variable_3'] = max_time_part.strip()
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_8(log):
    return "instruction" in log and "cache" in log and "parity" in log and "error" in log and "corrected" in log

def parse_log_template_8(log):
    try:
        return {
            'template_id': 8,
            'template': 'instruction cache parity error corrected',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 8,
            'template': 'instruction cache parity error corrected',
            'variables': {}
        }

def is_log_template_9(log):
    return "idoproxydb" in log and "hit ASSERT condition:" in log and "ASSERT expression=" in log

def parse_log_template_9(log):
    result = {
        'template_id': 9,
        'template': 'idoproxydb hit ASSERT condition: ASSERT expression=0 Source file=idotransportmgr.cpp Source line=<*> Function=int IdoTransportMgr::SendPacket(IdoUdpMgr*, BglCtlPavTrace*)',
        'variables': {}
    }
    try:
        parts = log.split('Source line=')
        if len(parts) != 2:
            return result
        source_line = parts[1].split()[0]
        result['variables']['source_line'] = source_line
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_10(log):
    return "data" in log and "storage" in log and "interrupt" in log

def parse_log_template_10(log):
    try:
        return {
            'template_id': 10,
            'template': 'data storage interrupt',
            'variables': {}
        }
    except Exception as e:
        return {
            'template_id': 10,
            'template': 'data storage interrupt',
            'variables': {}
        }

def is_log_template_11(log):
    return "ciod:" in log and "generated" in log and "core files" in log and "for program" in log

def parse_log_template_11(log):
    try:
        parts = log.split()
        if len(parts) < 8:
            return {'template_id': '11', 'template': 'ciod: generated <*> core files for program <*>'}
        count = int(parts[2])
        program_path = ' '.join(parts[7:])
        return {'template_id': '11', 'template': 'ciod: generated <*> core files for program <*>', 'count': count, 'program_path': program_path}
    except Exception as e:
        return {'template_id': '11', 'template': 'ciod: generated <*> core files for program <*>'}

def is_log_template_12(log):
    return "instruction address:" in log

def parse_log_template_12(log):
    result = {'template_id': 12, 'template': 'instruction address: <*>'}
    try:
        parts = log.split(': ')
        if len(parts) == 2 and parts[0] == 'instruction address':
            result['address'] = parts[1].strip()
        else:
            raise ValueError("Invalid log format")
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_13(log):
    return "ciod:" in log and "Error loading" in log and "invalid or missing program image" in log and "No such file or directory" in log

def parse_log_template_13(log):
    result = {
        'template_id': 13,
        'template': 'ciod: Error loading <*>: invalid or missing program image, No such file or directory'
    }
    try:
        parts = log.split(': Error loading ')[1].split(', No such file or directory')[0]
        result['variable'] = parts.strip()
    except IndexError:
        pass
    return result

def is_log_template_14(log):
    return "ciod:" in log and "Error loading" in log and "invalid or missing program image" in log and "Permission denied" in log

def parse_log_template_14(log):
    result = {'template_id': '14', 'template': 'ciod: Error loading /<*>: invalid or missing program image, Permission denied'}
    if not is_log_template_14(log):
        return result
    
    try:
        parts = log.split(':')
        if len(parts) < 2:
            return result
        
        path_part = parts[1].strip()
        if not path_part.startswith('Error loading'):
            return result
        
        path = path_part.split(' ')[2]
        result['path'] = path
    except Exception as e:
        print(f"Error parsing log: {e}")
    
    return result

def is_log_template_15(log):
    return "ciod:" in log and "LOGIN" in log and "failed:" in log and "such" in log and "file" in log

def parse_log_template_15(log):
    result = {
        'template_id': 15,
        'template': 'ciod: LOGIN chdir(<*>) failed: No such file or directory',
        'variables': {}
    }
    try:
        parts = log.split('chdir(')[1].split(')')[0].strip()
        result['variables']['path'] = parts
    except IndexError:
        pass
    return result

def is_log_template_16(log):
    return "ddr" in log and "errors(s)" in log and "detected and corrected" in log

def parse_log_template_16(log):
    result = {
        'template_id': 'template_16',
        'template': '<*> ddr errors(s) detected and corrected on rank <*>, symbol <*>, bit <*>'
    }
    try:
        parts = log.split()
        rank = int(parts[parts.index('rank') + 1])
        symbol = int(parts[parts.index('symbol') + 1])
        bit = int(parts[parts.index('bit') + 1])
        result['rank'] = rank
        result['symbol'] = symbol
        result['bit'] = bit
    except (ValueError, IndexError):
        pass
    return result

def is_log_template_17(log):
    return "ciod:" in log and "Error loading" in log and "invalid or missing program image" in log and "Exec format error" in log

def parse_log_template_17(log):
    result = {
        'template_id': 17,
        'template': 'ciod: Error loading /<*>: invalid or missing program image, Exec format error'
    }
    try:
        parts = log.split(':')
        if len(parts) > 1:
            path_part = parts[1].strip()
            if path_part.startswith('Error loading'):
                path_part = path_part[len('Error loading'):].strip()
                if '/' in path_part:
                    result['path'] = path_part.split('/')[1]
                else:
                    result['path'] = path_part
            else:
                result['path'] = None
        else:
            result['path'] = None
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_18(log):
    return "ciod:" in log and "Received signal" in log

def parse_log_template_18(log):
    result = {
        'template_id': 'template_18',
        'template': 'ciod: Received signal <*>, code=<*>, errno=<*>, address=<*>'
    }
    parts = log.split(', ')
    if len(parts) != 4:
        return result
    try:
        signal, code, errno, address = parts
        result['signal'] = int(signal.split(' ')[-1])
        result['code'] = int(code.split(' ')[-1])
        result['errno'] = int(errno.split(' ')[-1])
        result['address'] = address.split(' ')[-1]
    except ValueError:
        return result
    return result

def is_log_template_19(log):
    return "total of" in log and "ddr error(s)" in log and "detected and corrected" in log

def parse_log_template_19(log):
    try:
        parts = log.split()
        count = int(parts[3])
        return {
            'template_id': '19',
            'template': 'total of <*> ddr error(s) detected and corrected',
            'count': count
        }
    except (IndexError, ValueError):
        return {
            'template_id': '19',
            'template': 'total of <*> ddr error(s) detected and corrected'
        }

def is_log_template_20(log):
    return "Node card VPD check:" in log and "node" in log and "slot" in log and "do not match" in log and "VPD ecid" in log and "found" in log

def parse_log_template_20(log):
    result = {
        'template_id': '20',
        'template': 'Node card VPD check: U* node in processor card slot J* do not match. VPD ecid <*>, found <*>'
    }
    try:
        parts = log.split()
        for part in parts:
            if part.startswith('U') and part[1:].isdigit():
                result['node'] = part
            elif part.startswith('J') and part[1:].isdigit():
                result['slot'] = part
            elif 'VPD ecid' in part:
                result['ecid'] = part.split(',')[0].split()[-1]
            elif 'found' in part:
                result['found'] = part.split(',')[1].strip()
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_21(log):
    return "ciod:" in log and "Error reading message prefix" in log

def parse_log_template_21(log):
    result = {
        'template_id': 21,
        'template': 'ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket to <*>:<*>: Link has been severed'
    }
    parts = log.split()
    if len(parts) >= 8:
        try:
            ip = parts[7].split(':')[0]
            port = parts[7].split(':')[1]
            result['ip'] = ip
            result['port'] = port
        except (IndexError, ValueError):
            pass
    return result

def is_log_template_22(log):
    return "Lustre mount FAILED" in log and ":" in log and "point" in log

def parse_log_template_22(log):
    result = {'template_id': 22, 'template': 'Lustre mount FAILED : bglio<*> : point <*>'}
    if not is_log_template_22(log):
        return result
    
    parts = log.split(':')
    if len(parts) != 4:
        return result
    
    try:
        bglio = parts[2].strip()
        point = parts[3].strip().split()[0]
        result['bglio'] = bglio
        result['point'] = point
    except IndexError:
        pass
    
    return result

def is_log_template_23(log):
    return "Kernel detected" in log and "integer alignment exceptions" in log

def parse_log_template_23(log):
    result = {
        'template_id': '23',
        'template': 'Kernel detected <*> integer alignment exceptions (<*>) iar <*>, dear <*> (<*>) iar <*>, dear <*> (<*>) iar <*>, dear <*> (<*>) iar <*>, dear <*> (<*>) iar <*>, dear <*> (<*>) iar <*>, dear <*> (<*>) iar <*>, dear <*>'
    }
    if not is_log_template_23(log):
        return result
    
    parts = log.split()
    if len(parts) != 26:
        return result
    
    try:
        result['var1'] = int(parts[1])
        result['var2'] = int(parts[3])
        result['var3'] = int(parts[5])
        result['var4'] = int(parts[7])
        result['var5'] = int(parts[9])
        result['var6'] = int(parts[11])
        result['var7'] = int(parts[13])
        result['var8'] = int(parts[15])
        result['var9'] = int(parts[17])
        result['var10'] = int(parts[19])
        result['var11'] = int(parts[21])
        result['var12'] = int(parts[23])
        result['var13'] = int(parts[25])
        result['var14'] = int(parts[27])
        result['var15'] = int(parts[29])
        result['var16'] = int(parts[31])
        result['var17'] = int(parts[33])
        result['var18'] = int(parts[35])
        result['var19'] = int(parts[37])
        result['var20'] = int(parts[39])
        result['var21'] = int(parts[41])
        result['var22'] = int(parts[43])
        result['var23'] = int(parts[45])
        result['var24'] = int(parts[47])
        result['var25'] = int(parts[49])
    except ValueError:
        return result

def is_log_template_24(log):
    return "data address:" in log

def parse_log_template_24(log):
    try:
        parts = log.split("data address:")
        if len(parts) != 2:
            return {'template_id': 24, 'template': 'data address: <*>', 'address': None}
        address = parts[1].strip()
        return {'template_id': 24, 'template': 'data address: <*>', 'address': address}
    except Exception as e:
        return {'template_id': 24, 'template': 'data address: <*>', 'address': None}

def process_log(raw_line: str) -> Dict:
    """Master router function"""
    if is_log_template_0(raw_line):
        return parse_log_template_0(raw_line)
    if is_log_template_1(raw_line):
        return parse_log_template_1(raw_line)
    if is_log_template_2(raw_line):
        return parse_log_template_2(raw_line)
    if is_log_template_3(raw_line):
        return parse_log_template_3(raw_line)
    if is_log_template_4(raw_line):
        return parse_log_template_4(raw_line)
    if is_log_template_5(raw_line):
        return parse_log_template_5(raw_line)
    if is_log_template_6(raw_line):
        return parse_log_template_6(raw_line)
    if is_log_template_7(raw_line):
        return parse_log_template_7(raw_line)
    if is_log_template_8(raw_line):
        return parse_log_template_8(raw_line)
    if is_log_template_9(raw_line):
        return parse_log_template_9(raw_line)
    if is_log_template_10(raw_line):
        return parse_log_template_10(raw_line)
    if is_log_template_11(raw_line):
        return parse_log_template_11(raw_line)
    if is_log_template_12(raw_line):
        return parse_log_template_12(raw_line)
    if is_log_template_13(raw_line):
        return parse_log_template_13(raw_line)
    if is_log_template_14(raw_line):
        return parse_log_template_14(raw_line)
    if is_log_template_15(raw_line):
        return parse_log_template_15(raw_line)
    if is_log_template_16(raw_line):
        return parse_log_template_16(raw_line)
    if is_log_template_17(raw_line):
        return parse_log_template_17(raw_line)
    if is_log_template_18(raw_line):
        return parse_log_template_18(raw_line)
    if is_log_template_19(raw_line):
        return parse_log_template_19(raw_line)
    if is_log_template_20(raw_line):
        return parse_log_template_20(raw_line)
    if is_log_template_21(raw_line):
        return parse_log_template_21(raw_line)
    if is_log_template_22(raw_line):
        return parse_log_template_22(raw_line)
    if is_log_template_23(raw_line):
        return parse_log_template_23(raw_line)
    if is_log_template_24(raw_line):
        return parse_log_template_24(raw_line)
    else:
        return {'template_id': -1, 'template': 'UNKNOWN', 'raw': raw_line}
