"""
Parser Bank for Apache_2k
Generated by QwenLog
Model: Qwen2.5-Coder-7B
Generated: 2026-01-20 20:09:38
Templates: 6
"""

from typing import Dict, Optional

def is_log_template_0(log):
    return "jk2_init()" in log and "Found child" in log and "scoreboard slot" in log

def parse_log_template_0(log):
    result = {'template_id': 0, 'template': 'jk2_init() Found child <*> in scoreboard slot <*>'}
    if not is_log_template_0(log):
        return result
    
    parts = log.split()
    try:
        child_index = parts.index('child') + 1
        slot_index = parts.index('slot') + 1
        result['child'] = parts[child_index]
        result['slot'] = parts[slot_index]
    except (ValueError, IndexError):
        pass
    
    return result

def is_log_template_1(log_line):
    return "workerEnv.init()" in log_line

def parse_log_template_1(log_line):
    result = {'template_id': 1, 'template': 'workerEnv.init() ok <*>'}
    if not is_log_template_1(log_line):
        return result
    try:
        parts = log_line.split()
        if len(parts) > 2:
            result['variable'] = parts[2]
        else:
            result['variable'] = None
    except Exception as e:
        print(f"Error parsing log: {e}")
    return result

def is_log_template_2(log):
    return "mod_jk" in log and "child" in log and "workerEnv" in log and "error state" in log

def parse_log_template_2(log):
    try:
        parts = log.split()
        if len(parts) >= 5 and "mod_jk" in parts[0] and "child" in parts[1] and "workerEnv" in parts[2] and "error state" in parts[3]:
            return {
                'template_id': 2,
                'template': 'mod_jk child workerEnv in error state <*>',
                'variable': int(parts[4])
            }
    except Exception as e:
        print(f"Error parsing log: {e}")
    return {
        'template_id': 2,
        'template': 'mod_jk child workerEnv in error state <*>',
        'variable': None
    }

def is_log_template_3(log):
    return '[client' in log and 'Directory index forbidden by rule:' in log

def parse_log_template_3(log):
    try:
        parts = log.split(']')
        client_part = parts[0].split(' ')[1]
        rule_part = parts[1].split(': ')[1]
        return {
            'template_id': 3,
            'template': '[client <*>] Directory index forbidden by rule: <*>',
            'client_ip': client_part,
            'forbidden_directory': rule_part
        }
    except (IndexError, ValueError):
        return {
            'template_id': 3,
            'template': '[client <*>] Directory index forbidden by rule: <*>'
        }

def is_log_template_4(log):
    return "jk2_init()" in log and "Can't find child" in log and "scoreboard" in log

def parse_log_template_4(log):
    try:
        parts = log.split()
        if len(parts) >= 6 and parts[2] == "Can't" and parts[3] == "find" and parts[4] == "child":
            return {
                'template_id': 4,
                'template': 'jk2_init() Can\'t find child <*> in scoreboard',
                'child_id': int(parts[5])
            }
    except (IndexError, ValueError):
        pass
    return {
        'template_id': 4,
        'template': 'jk2_init() Can\'t find child <*> in scoreboard'
    }

def is_log_template_5(log):
    return "mod_jk" in log and "child" in log and "init" in log

def parse_log_template_5(log):
    try:
        parts = log.split()
        if len(parts) < 5:
            return {'template_id': 5, 'template': 'mod_jk child init <*> <*>'}
        return {
            'template_id': 5,
            'template': 'mod_jk child init <*> <*>',
            'var1': parts[3],
            'var2': parts[4]
        }
    except Exception as e:
        return {'template_id': 5, 'template': 'mod_jk child init <*> <*>'}

def process_log(raw_line: str) -> Dict:
    """Master router function"""
    if is_log_template_0(raw_line):
        return parse_log_template_0(raw_line)
    if is_log_template_1(raw_line):
        return parse_log_template_1(raw_line)
    if is_log_template_2(raw_line):
        return parse_log_template_2(raw_line)
    if is_log_template_3(raw_line):
        return parse_log_template_3(raw_line)
    if is_log_template_4(raw_line):
        return parse_log_template_4(raw_line)
    if is_log_template_5(raw_line):
        return parse_log_template_5(raw_line)
    else:
        return {'template_id': -1, 'template': 'UNKNOWN', 'raw': raw_line}
